name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'AttendancePortal'
  AZURE_WEBAPP_SLOT_NAME: 'production'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore NuGet Packages
      run: |
        cd AttendancePortal
        dotnet restore

    - name: Build the app
      run: |
        cd AttendancePortal
        dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Publish the app
      run: |
        cd AttendancePortal
        dotnet publish --configuration ${{ env.BUILD_CONFIGURATION }} --output $(System.DefaultWorkingDirectory)/bin/Release/net5.0/publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      env:
        AZURE_WEBAPP_PACKAGE_PATH: $(System.DefaultWorkingDirectory)/bin/Release/net5.0/publish
