name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  WEBAPP_URL: ${{ secrets.WEBAPP_URL }}

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and publish
      run: |
        cd attendanceportal
        dotnet build --configuration Release
        dotnet publish --configuration Release --output /tmp/publish

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: attendanceportal
        path: /tmp/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'attendanceportal'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/attendanceportal
        slot-name: 'production'
        action: 'swap'
        resource-group: 'myresourcegroup'
        timeout: '3600'
